name: Auto Update Market JSON

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true   # <— allow pushes

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Generate market_status.json
        run: python generate_json.py

      - name: Commit & Push updated JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add market_status.json
          git commit -m "Auto-update market_status.json" || echo "No changes"
          git push
