name: Auto Update Market JSON

on:
  schedule:
    - cron: '*/5 * * * *'    # every 5 minutes
  workflow_dispatch:        # manual trigger

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # allow pushes
          persist-credentials: true           # keep the token for git commands
          fetch-depth: 0                      # full history for commits

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Generate market_status.json
        run: python generate_json.py

      - name: Commit & Push updated JSON
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: actions@github.com
          message: Auto-update market_status.json
          add: market_status.json
